name: Python Caching Workflow

on: push

jobs:
  build-fast:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip and site-packages
      uses: actions/cache@v4
      id: cache
      with:
        path: |
          ~/.cache/pip
          /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages
        key: ${{ runner.os }}-python3.11-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python3.11-

    - name: Install dependencies
      run: |
        # Install dependencies only if the cache did not restore all necessary packages
        python -c "import tensorflow, pandas, numpy, matplotlib, jupyterlab, pyarrow, great_expectations, streamlit" || pip install -r requirements.txt

    - name: Test installed packages 2
      run: |
        python -c "import tensorflow; print(tensorflow.__version__)"
        python -c "import pandas as pd; print(pd.__version__)"
        python -c "import numpy; print(numpy.__version__)"
        python -c "import matplotlib; print(matplotlib.__version__)"
        python -c "import jupyterlab; print(jupyterlab.__version__)"
        python -c "import pyarrow; print(pyarrow.__version__)"
        python -c "import great_expectations; print(great_expectations.__version__)"
        python -c "import streamlit; print(streamlit.__version__)"

  build-slow:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python 3.11 2
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies 
      run: pip install -r requirements.txt

    - name: Test installed packages
      run: |
        python -c "import tensorflow; print(tensorflow.__version__)"
        python -c "import pandas as pd; print(pd.__version__)"
        python -c "import numpy; print(numpy.__version__)"
        python -c "import matplotlib; print(matplotlib.__version__)"
        python -c "import jupyterlab; print(jupyterlab.__version__)"
        python -c "import pyarrow; print(pyarrow.__version__)"
        python -c "import great_expectations; print(great_expectations.__version__)"
        python -c "import streamlit; print(streamlit.__version__)"