name: Python Caching Workflow

on: push

jobs:
  build-fast:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache full pip install
      uses: actions/cache@v4
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ hashFiles('requirements.txt') }}

    - name: Install dependencies
      run: pip install -r requirements.txt 

  build-slow:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies 2
      run: pip install -r requirements.txt
