name: Python Caching Workflow

on: push

jobs:
  build-fast:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Check directory size
      run: du -sh ${{ env.pythonLocation }}

    - name: Cache full pip install
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.pythonLocation }}/lib/python3.11/site-packages
          ~/.cache/pip
        key: ${{ runner.os }}-python3.11-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python3.11-

    - name: Install dependencies
      run: |
        if [ -d ${{ env.pythonLocation }}/lib/python3.11/site-packages ]; then
          echo "Using cached dependencies"
        else
          pip install -r requirements.txt
        fi

    - name: Test installed packages
      run: |
        python -c "import tensorflow; print(tensorflow.__version__)"
        python -c "import pandas as pd; print(pd.__version__)"
        python -c "import numpy; print(numpy.__version__)"
        python -c "import matplotlib; print(matplotlib.__version__)"
        python -c "import jupyterlab; print(jupyterlab.__version__)"
        python -c "import pyarrow; print(pyarrow.__version__)"
        python -c "import great_expectations; print(great_expectations.__version__)"
        python -c "import streamlit; print(streamlit.__version__)"

  build-slow:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up Python 3.11 2
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies 
      run: pip install -r requirements.txt

    - name: Test installed packages
      run: |
        python -c "import tensorflow; print(tensorflow.__version__)"
        python -c "import pandas as pd; print(pd.__version__)"
        python -c "import numpy; print(numpy.__version__)"
        python -c "import matplotlib; print(matplotlib.__version__)"
        python -c "import jupyterlab; print(jupyterlab.__version__)"
        python -c "import pyarrow; print(pyarrow.__version__)"
        python -c "import great_expectations; print(great_expectations.__version__)"
        python -c "import streamlit; print(streamlit.__version__)"